In [23]:
from numpy import dot,sqrt,array,eye,zeros_like,cos,sin,diag,exp,pi
from numpy.linalg import solve
from math import *
import numpy as np
import pandas as pd 
from tabulate import tabulate
import sympy as sym
from fractions import Fraction as fr

In [24]:
def v(a):
    e1 = np.zeros(len(a))
    e1[0] = 1
    print("**************************************")
    print("La norma : ",np.linalg.norm(a))
    print("El vector :")
    return a+np.sign(a[0])*np.linalg.norm(a)*e1

In [25]:
def calcH1(v):
    n = len(v)
    I=np.identity(n)
    
    num = 2*((v*v.T))
    den = np.linalg.norm(v)**2
    print("Num\n" ,num)
    print("Den\n",den)
    H = I -num/den
    return H
A = array([[1,1],[1,-1],[1,-2]])
col = array([[1],[1],[1]])
v1 = v(col)
print(v1)
# v1 = a1 + sgn(a[1][1])*//a1//*e1
H = calcH1(v1)
print("H\n: ",H)
A1 = H@A
print("A1\n: ",A1)

print("************************************")


**************************************
La norma :  1.7320508075688772
El vector :
[[2.73205081 1.         1.        ]
 [2.73205081 1.         1.        ]
 [2.73205081 1.         1.        ]]
Num
 [[14.92820323  5.46410162  5.46410162]
 [ 5.46410162  2.          2.        ]
 [ 5.46410162  2.          2.        ]]
Den
 28.392304845413264
H
:  [[ 0.47421658 -0.19245009 -0.19245009]
 [-0.19245009  0.92955838 -0.07044162]
 [-0.19245009 -0.07044162  0.92955838]]
A1
:  [[ 0.0893164   1.05156685]
 [ 0.66666667 -0.98112522]
 [ 0.66666667 -1.98112522]]
************************************


In [26]:
col = array([[1],[1],[1]])
v1 = v(col)
print(v1)
# v1 = a1 + sgn(a[1][1])*//a1//*e1
H = calcH1(v1)
print(H)

**************************************
La norma :  1.7320508075688772
El vector :
[[2.73205081 1.         1.        ]
 [2.73205081 1.         1.        ]
 [2.73205081 1.         1.        ]]
Num
 [[14.92820323  5.46410162  5.46410162]
 [ 5.46410162  2.          2.        ]
 [ 5.46410162  2.          2.        ]]
Den
 28.392304845413264
[[ 0.47421658 -0.19245009 -0.19245009]
 [-0.19245009  0.92955838 -0.07044162]
 [-0.19245009 -0.07044162  0.92955838]]


In [27]:
Q = array([[-0.801883725737,-0.2672612419124244,0,-0.534522483],
       [-0.16695677422593,-0.2504351613389,0.876523064686166,0.3756527420],
       [-0.56931791003233,0.340734865279366,-0.3040641590539,0.6836094324]])


b = array([[1],[2],[0],[3]])

print(Q@b)

[[-2.93997366]
 [ 0.45913113]
 [ 2.16298012]]
